Bend/usuario api
No-Country/c17-48-n-java pull request #37
Opened 2024-04-18 05:31 UTC by wilosorio20

se manda pull para la revision y union de la rama

2024-04-18 10:55 UTC, sirnas1983 requested changes

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/controller/usuario/UsuarioController.java
> +            return usuarioService.buscarUserDTO(page, size);
Aqui podrias directamente pasar el pageable como parametro

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/controller/usuario/UsuarioController.java
> +            return usuarioService.buscarUserDTO(page, size);
Las excepciones puedes manejarla a donde se te produzca. Recuerda esta la clase GlobalExceptionHandler que se encarga de "transformar" las excpeciones

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/controller/usuario/UsuarioController.java
> +    private UserDTO convertirAUsuarioDTO(Usuario usuario) {
En este metodo solicitas el id como pathVariable, pero en ningun momento lo usas... Este metodo deberia llamar a un metodo en el servicio que reciba el id como parametro para hacer la consulta a traves de JPA

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/controller/usuario/UsuarioController.java
> +    public ResponseEntity<Usuario> crearUsuario(@RequestBody UserDTO usuarioDTO, Usuario usuarioExistente) {
Aqui el segundo parametro no tiene mucho sentido mantenerlo. Podrias usar el @Valid entre @RequestBody y UserDTO para que Spring valide la integridad del body contra la estructura de UserDTO. Usar el @Valid permite controlar que el objeto enviado a traves del body de la solicitud tenga la misma estructura y tipo de datos que el declarado como tipo de dato (en este caso UserDTO)

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/controller/usuario/UsuarioController.java
> +        try {
Toda esta logica es mas de la capa de servicio que de la capa de controlador. Deberia ir dentro de un metodo del servicio, por un tema de responsabilidades mas que nada. El controlador se encarga de mapear las solicitudes con los servicios correspondientes.

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/controller/usuario/UsuarioController.java
> +        public ResponseEntity<String> eliminarUsuario(@PathVariable UUID id) {
Mismo caso que anterior

2024-04-18 10:55 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/model/Usuario.java
> +    public void setId(org.hibernate.validator.constraints.UUID id) {
Creo que no deberiamos dejar que el ID se pueda cambiar. De ultima puedes hacer 2 userDTO, uno para la creacion/modificacion y otro para enviar la informacion

2024-04-19 00:17 UTC, sirnas1983 requested changes

2024-04-19 00:17 UTC, sirnas1983 commented on backend/adopcion/src/main/java/com/mascotas/adopcion/service/usuario/UsuarioService.java
No deberiamos tener @PostMapping aqui. Aqui deberia estar toda la logica de negocios unicamente. de la fila 51 a la 105 creo que no va.

2024-04-19 14:23 UTC, sirnas1983 approved these changes

2024-04-19 17:32 UTC, l1facu approved these changes

2024-04-19 17:45 UTC, closed without merging